In [1]:
import json
import pandas as pd

# Load JSON manually
with open(r"v2_OpenEnded_mscoco_train2014_questions.json", "r") as f:
    data = json.load(f)

# Extract the list of questions
qn_json = pd.DataFrame(data["questions"])

print(qn_json.shape)
qn_json.head()

(443757, 3)

   image_id                                     question  question_id
0    458752    What is this photo taken looking through?    458752000
1    458752           What position is this man playing?    458752001
2    458752             What color is the players shirt?    458752002
3    458752  Is this man a professional baseball player?    458752003
4    262146                      What color is the snow?    262146000

In [2]:

# Load JSON manually
with open(r"v2_mscoco_train2014_annotations.json", "r") as f:
    data = json.load(f)

# Extract the list of annotations
qn_json = pd.DataFrame(data["annotations"])
qn_json = qn_json[["question_type", "multiple_choice_answer","image_id","question_id"]]
qn_json.head()

       question_type multiple_choice_answer  image_id  question_id
0       what is this                    net    458752    458752000
1               what                pitcher    458752    458752001
2  what color is the                 orange    458752    458752002
3            is this                    yes    458752    458752003
4  what color is the                  white    262146    262146000